d = [
  {
    "ID":1,
    "long":-85.751944,
    "lat":38.243056,
    "name":"Adath Jeshurun Temple and School",
    "short_description":"The Temple is a most fitting example of the work of W.J. Dodd (1862-1930), one of the finest and most influential architects in Louisville's history.",
    "street_address":"757 S. Brook St.",
    "zip":40203,
    "image_filename":"001_adath_jeshurun_temple.jpg",
    "moreinfo_link":"http://en.wikipedia.org/wiki/Adath_Jeshurun_Temple_and_School",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/74000882.pdf",
    "year_built":1905,
    "year_listed":1982,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/File:Adath_Jeshurun_Temple_in_Louisville.jpg",
    "nrhp_reference":74000882,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":2,
    "long":-85.757778,
    "lat":38.255278,
    "name":"Almsted Brothers Building",
    "short_description":"The Almstedt Brothers Building, designed by the architectural firm Joseph and Joseph, is an excellent example of the Beaux Arts style applied to a small-scale city structure. The outstanding detailing and well organized classical composition make it one of the finest classical revival commercial structures in downtown Louisville.",
    "street_address":"425 W. Market St.",
    "zip":40202,
    "image_filename":"002_almsted_brothers_building.jpg",
    "moreinfo_link":"http://en.wikipedia.org/wiki/Almsted_Brothers_Building",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/82002704.pdf",
    "year_built":1930,
    "year_listed":1982,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/File:Louisville,_KY_-_Almsted_Brothers_Building.jpg",
    "nrhp_reference":82002704,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":3,
    "long":-85.762778,
    "lat":38.246667,
    "name":"Ancient and Accepted Scottish Rite Temple",
    "short_description":"The Scottish Rite Temple is an important example of the. pure Neo-classical Revival style, Both the interior and exterior are unaltered and, as such, the building represents one of the finest examples of its type in Louisville.",
    "street_address":"200 E. Gray St.",
    "zip":40202,
    "image_filename":"003_ancient_and_accepted_scottish_rite_temple.jpg",
    "moreinfo_link":"http://en.wikipedia.org/wiki/Ancient_and_Accepted_Scottish_Rite_Temple",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/82002705.pdf",
    "year_built":1930,
    "year_listed":1982,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/File:AncientandAcceptedScottishRiteTempleLouisville.jpg",
    "nrhp_reference":82002705,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":4,
    "long":-85.756111,
    "lat":38.261111,
    "name":"Belle of Louisville",
    "short_description":"The steamer Belle of Louisville is the last remaining traditional Mississippi River stern wheel steamboat in operation. She is further being operated by the City of Louisville and Jefferson County from April to October each year in the same type of service for which she was built in 1914. She is powered by her original engines and the same type of boilers that she was built with.\n\n",
    "street_address":"401 West River Road",
    "zip":40202,
    "image_filename":"004_belle_of_louisville.jpg",
    "moreinfo_link":"http://www.belleoflouisville.org/",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/72000535.pdf",
    "year_built":1914,
    "year_listed":1972,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://upload.wikimedia.org/wikipedia/commons/5/51/Belle_of_Louisville_2.jpg",
    "nrhp_reference":72000535,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":5,
    "long":-85.754722,
    "lat":38.251944,
    "name":"Bosler Fireproof Garage",
    "short_description":"The Bosler Fireproof Garage is a boldly designed, Romanesque Revival structure, representing a creative architectural solution to a utilitarian purpose. It is the oldest known parking garage remaining in Louisville.",
    "street_address":"423 S. 3rd St.",
    "zip":40202,
    "image_filename":"005_bosler_garage.jpg",
    "moreinfo_link":"http://digital.library.louisville.edu/cdm/singleitem/collection/cs/id/815/rec/4",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/83002639.pdf",
    "year_built":1919,
    "year_listed":1983,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://commons.wikimedia.org/wiki/File:BoslerGarageLouisville.jpg",
    "nrhp_reference":83002639,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":6,
    "long":-85.749167,
    "lat":38.245,
    "name":"Brandeis House",
    "short_description":"The Brandeis House is locally significant as the boyhood home of Louis E. Brandeis, esteemed United States Supreme Court Justice, the first Jewish Supreme Court Justice in the nation's history, and a zealous advocate of housing desegregation in the early twentieth century. Since 1913 it has been home to the Louisville Turners, a leading sociocultural organization in Louisville.",
    "street_address":"310 E. Broadway",
    "zip":40202,
    "image_filename":"006_brandeis_house.jpg",
    "moreinfo_link":"http://en.wikipedia.org/wiki/Brandeis_House_(Louisville,_Kentucky)",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/84001553.pdf",
    "year_built":1864,
    "year_listed":1984,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.m.wikipedia.org/wiki/File:Brandeis_House_in_Louisville.jpg",
    "nrhp_reference":84001553,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":7,
    "long":-85.757778,
    "lat":38.246667,
    "name":"Brown Hotel Building and Theater",
    "short_description":"The Brown Hotel is an outstanding example of hotel architecture. It was built by James Graham Brown (1881-1969], a Louisville businessman and philanthropist. The building represents the rise of Broadway to a strong commercial district as it was followed by the Heyburn Building, The Fincastle Building, and The Martin Brown Building (later The Commonwealth Building).",
    "street_address":"335 W. Broadway",
    "zip":40202,
    "image_filename":"007_brown_hotel.jpg",
    "moreinfo_link":"http://en.wikipedia.org/wiki/Brown_Hotel_(Louisville,_Kentucky)",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/78001346.pdf",
    "year_built":1923,
    "year_listed":1978,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/Brown_Hotel_(Louisville,_Kentucky)",
    "nrhp_reference":78001346,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":8,
    "long":-85.756944,
    "lat":38.246389,
    "name":"Breslin Building",
    "short_description":"The delicate, Renaissance-inspired bas-reliefs in terra cotta which adorn the Breslin Building are a hallmark of the work of one of Louisville's major architectural firms of the 1920s, Joseph & Joseph. The structure is one of several important commercial buildings to remain on Broadway, the city's most important commercial hub of this period.",
    "street_address":"305 W. Broadway",
    "zip":40202,
    "image_filename":"008_breslin_building.jpg",
    "moreinfo_link":"http://www.nps.gov/history/nr/feature/places/83004589.htm",
    "pdf_link":"http://www.nps.gov/history/nr/feature/places/pdfs/83004589.pdf",
    "year_built":1927,
    "year_listed":2013,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/File:Breslin_Building_in_Louisville.jpg",
    "nrhp_reference":83004589,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":9,
    "long":-85.751944,
    "lat":38.256389,
    "name":"J.T.S. Brown and Son's Complex",
    "short_description":"The J. T. S Brown & Son's complex is architecturally significant because of its apparent association with Henry Whitestone and D. X. Murphy, two of Louisville's most creative and prolific architects of the nineteenth and early twentieth centuries, and because of the artistic use of cast iron and terra cotta as decorative building materials.",
    "street_address":"105 W. Main St.",
    "zip":40202,
    "image_filename":"009_jts_brown_sons_complex.jpg",
    "moreinfo_link":"http://pre-prowhiskeymen.blogspot.com/2012/05/jts-brown-and-his-grand-kentucky-clan.html",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/98001489.pdf",
    "year_built":1877,
    "year_listed":1998,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/File:J.T.S._Brown_and_Son%27s_Complex.jpg",
    "nrhp_reference":98001489,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":10,
    "long":-85.758611,
    "lat":38.251389,
    "name":"The Business Women's Club",
    "short_description":"The Business Women's Club is a building located on Muhammad Ali Boulevard in Downtown Louisville, Kentucky. It was placed on the National Register of Historic Places on February 7, 2008. It was co-founded by Jennie Benedict in 1899.",
    "street_address":"425 Muhammad Ali Blvd.",
    "zip":40202,
    "image_filename":"010_business_womans_club.jpg",
    "moreinfo_link":"http://en.wikipedia.org/wiki/Business_Women%27s_Club",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/08000006.pdf",
    "year_built":1911,
    "year_listed":2008,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/File:BusinessWomansCLubLouisville.jpg",
    "nrhp_reference":8000006,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":11,
    "long":-85.758889,
    "lat":38.251111,
    "name":"Walnut Street Theater",
    "short_description":"The Walnut Street Theatre is an important architectural element in the early twentieth century development of downtown Louisville. The building also may be one of the early vaudeville houses of the famous theatre designer John Eberson. The shifts in use of the theatre from vaudeville, to legitimate stage, to film characterizes the evolution in entertainment media which the American public patronized through this century.",
    "street_address":"416 W. Walnut St.",
    "zip":40202,
    "image_filename":"076_walnut_street_theatre.jpg",
    "moreinfo_link":"http://cinematreasures.org/theaters/16591",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/78001370.pdf",
    "year_built":1910,
    "year_listed":1978,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/File:WalnutStreetTHeatreLouisville.jpg",
    "nrhp_reference":78001370,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":12,
    "long":-85.722222,
    "lat":38.248333,
    "name":"Union Monument in Louisville",
    "short_description":"This simple monument was erected in 1914 adjacent to the portion of Cave Hill Cemetery that contains the burials of Civil War soldiers. It was erected by other Kentucky Union veterans to commemorate those unknown soldiers buried in the plot.",
    "street_address":"Cave Hill Cemetary",
    "zip":40204,
    "image_filename":"106_union_monument.jpg",
    "moreinfo_link":"http://en.wikipedia.org/wiki/Union_Monument_in_Louisville",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/97000687.pdf",
    "year_built":1914,
    "year_listed":1997,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/File:Union_Monument_in_Louisville.jpg",
    "nrhp_reference":97000687,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":13,
    "long":-85.758611,
    "lat":38.243333,
    "name":"Calvary Episcopal Church",
    "short_description":"Calvary Episcopal Church is significant in having preserved to a large degree the flavor of the Victorian Gothic Revival. It remains today as one of the most distinctive and best preserved of the series of churches erected in Louisville during the late 19th century (five of these being on Fourth Street). From the beginning, the structure was intended to be among the country's most magnificent edifices.",
    "street_address":"812 S. 4th St.",
    "zip":40203,
    "image_filename":"113_calvary_episcopal_church.jpg",
    "moreinfo_link":"http://en.wikipedia.org/wiki/Calvary_Episcopal_Church_(Louisville,_Kentucky)",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/78001347.pdf",
    "year_built":1874,
    "year_listed":1971,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/File:Calvary_Episcopal_Church_in_Louisville_from_northwest.jpg",
    "nrhp_reference":78001347,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":14,
    "long":-85.758333,
    "lat":38.243889,
    "name":"Church of the Messiah",
    "short_description":"The First Unitarian Church of Louisville (known as the Church of the Messiah for approximately fifty years after the acquisition of the assets of the former Universalist Church made possible the construction of the present building) has a long history of religious, intellectual, and social-humanitarian contribution to the community.",
    "street_address":"805 S. 4th St.",
    "zip":40203,
    "image_filename":"114_church_of_the_messiah.jpg",
    "moreinfo_link":"http://digital.library.louisville.edu/cdm/singleitem/collection/cs/id/1305/rec/12",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/76000903.pdf",
    "year_built":1872,
    "year_listed":1976,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://commons.wikimedia.org/wiki/File:Church_of_the_Messiah,_First_Unitarian-Universalist_Church.jpg",
    "nrhp_reference":76000903,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":15,
    "long":-85.757222,
    "lat":38.241944,
    "name":"The Olympic",
    "short_description":"A mixed-use commercial/residential complex constructed in 1926-27 in the Commercial Craftsman style.",
    "street_address":"223 W. Breckinridge St.",
    "zip":40203,
    "image_filename":"133_the_olympic.jpg",
    "moreinfo_link":"http://en.wikipedia.org/wiki/National_Register_of_Historic_Places_listings_in_Old_Louisville,_Kentucky",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/07000677.pdf",
    "year_built":1926,
    "year_listed":2007,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/File:The_Olympic_in_Louisville.jpg",
    "nrhp_reference":7000677,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":16,
    "long":-85.775278,
    "lat":38.247778,
    "name":"Whiteside Bakery",
    "short_description":"Whiteside Bakery was built in 1908 at the request of bakery magnate I. F. Whiteside. At the time of its dedication, it was hailed as the largest, most sophisticated bakery in the United States. Designed in the Mission Style by prominent Louisville architect Arthur Loomis, the bakery inspired admiration from its inception for its aesthetic, as well as its technological, merits. It is one of a very few structures representing the Mission Style in the Louisville area.",
    "street_address":"1400 West Broadway St.",
    "zip":40203,
    "image_filename":"188_whiteside_bakery.jpg",
    "moreinfo_link":"http://placestogobuildingstosee.blogspot.com/2011/05/whiteside-bakery-louisville-kentucky.html",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/79001014.pdf",
    "year_built":1908,
    "year_listed":1979,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/File:Whiteside_Bakery.jpg",
    "nrhp_reference":79001014,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":17,
    "long":-85.765,
    "lat":38.225833,
    "name":"Steam Engine Company No. 18",
    "short_description":"",
    "street_address":"2600 S. 4th St.",
    "zip":40208,
    "image_filename":"366_firehouse_18.jpg",
    "moreinfo_link":"http://en.wikipedia.org/wiki/Historic_Firehouses_of_Louisville",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/80001624.pdf",
    "year_built":1904,
    "year_listed":1980,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/File:FireHouse_18_Louisville.jpg",
    "nrhp_reference":80001624,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":18,
    "long":-85.749722,
    "lat":38.230556,
    "name":"George H. Tingley Elementary School",
    "short_description":"Tingley Elementary School plays an important role in the South Preston Street streetscape and is an important neighborhood landmarks. Its architectural design and quality of craftsmanship, evident in the building's facade, create an important addition to the architectural integrity of the surrounding area, Tingley Elementary, built in 1892, is an excellent local example of the Romanesque Revival Style.",
    "street_address":"1311 S. Preston St.",
    "zip":40208,
    "image_filename":"379_george_h_tingley_elementary_school.jpg",
    "moreinfo_link":"http://www.archiplanet.org/wiki/Tingley,_George_H.,_Elementary_School",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/84001586.pdf",
    "year_built":1892,
    "year_listed":1984,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://en.wikipedia.org/wiki/File:George_H._Tingley_Elementary_School.jpg",
    "nrhp_reference":84001586,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":19,
    "long":-85.766667,
    "lat":38.258611,
    "name":"Tobacco Realty Company",
    "short_description":"Built in,1912 as a tobacco warehouse, the building had storage capacity of 3000 hogsheads and cost $150,000. The present owner has been located here since 1927. It was built on the Former site of the A.V. Dupont Paper Mill.",
    "street_address":"118 N. 10th St.",
    "zip":40202,
    "image_filename":"429_tobacco_realty_company.jpg",
    "moreinfo_link":"http://gohistoric.com/places/tobacco-realty-company-louisville",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/83002742.pdf",
    "year_built":1912,
    "year_listed":1983,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://commons.wikimedia.org/wiki/File:Tobacco_Realty_Company.jpg",
    "nrhp_reference":83002742,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  },
  {
    "ID":20,
    "long":-85.758056,
    "lat":38.249167,
    "name":"Caperton Block",
    "short_description":"The Caperton Block was constructed in 1883-1885 in the Renaissance Revival style and is one of the best local examples of that style, particularly on such a grand scale. The Caperton Block was first owned by Mary E. Caperton, daughter of the prominent Louisvillian James Guthrie, The structure is recognized as an integral part of Louisville's, central business district and is an important element in the streetscape of the Fourth Avenue-Chestnut Street intersections.\n\n",
    "street_address":"564 4th Ave.",
    "zip":40202,
    "image_filename":"020_caperton_block.jpg",
    "moreinfo_link":"http://brokensidewalk.com/2010/01/29/photo-tour-inside-fourth-streets-caperton-block/",
    "pdf_link":"http://pdfhost.focus.nps.gov/docs/NRHP/Text/84001554.pdf",
    "year_built":1883,
    "year_listed":1984,
    "photo_source_name":"Wikimedia Commons",
    "photo_source_url":"http://commons.wikimedia.org/wiki/File:CapertonBlockLouisville.jpg",
    "nrhp_reference":84001554,
    "FIELD16":"",
    "FIELD17":"",
    "FIELD18":"",
    "FIELD19":"",
    "FIELD20":""
  }
]
